"""
Manually written protobuf message classes matching proto/mlx_container.proto.

In production, these would be auto-generated by protoc. This manual implementation
allows the package to work without requiring protoc at build time.
"""

# Re-export for compatibility with the standard protoc-generated naming
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import symbol_database as _symbol_database


class _SimpleMessage:
    """Base class providing HasField for oneof-like fields."""
    def HasField(self, field_name):
        return hasattr(self, f"_{field_name}_set") and getattr(self, f"_{field_name}_set", False)

    def SerializeToString(self):
        raise NotImplementedError("Use grpc serialization")

    @classmethod
    def FromString(cls, data):
        raise NotImplementedError("Use grpc deserialization")


class LoadModelRequest(_SimpleMessage):
    def __init__(self, model_id="", alias="", memory_budget_bytes=0, **kwargs):
        self.model_id = model_id
        self.alias = alias
        self.memory_budget_bytes = memory_budget_bytes


class LoadModelResponse(_SimpleMessage):
    def __init__(self, success=False, model_id="", error="", memory_used_bytes=0, load_time_seconds=0.0, **kwargs):
        self.success = success
        self.model_id = model_id
        self.error = error
        self.memory_used_bytes = memory_used_bytes
        self.load_time_seconds = load_time_seconds


class UnloadModelRequest(_SimpleMessage):
    def __init__(self, model_id="", **kwargs):
        self.model_id = model_id


class UnloadModelResponse(_SimpleMessage):
    def __init__(self, success=False, error="", memory_freed_bytes=0, **kwargs):
        self.success = success
        self.error = error
        self.memory_freed_bytes = memory_freed_bytes


class ListModelsRequest(_SimpleMessage):
    def __init__(self, **kwargs):
        pass


class ListModelsResponse(_SimpleMessage):
    def __init__(self, models=None, **kwargs):
        self.models = models or []


class ModelInfo(_SimpleMessage):
    def __init__(self, model_id="", alias="", memory_used_bytes=0, is_loaded=False, model_type="", **kwargs):
        self.model_id = model_id
        self.alias = alias
        self.memory_used_bytes = memory_used_bytes
        self.is_loaded = is_loaded
        self.model_type = model_type


class ChatMessage(_SimpleMessage):
    def __init__(self, role="", content="", **kwargs):
        self.role = role
        self.content = content


class GenerateParameters(_SimpleMessage):
    def __init__(self, max_tokens=0, temperature=0.0, top_p=0.0, repetition_penalty=0.0, repetition_context_size=0, **kwargs):
        self.max_tokens = max_tokens
        self.temperature = temperature
        self.top_p = top_p
        self.repetition_penalty = repetition_penalty
        self.repetition_context_size = repetition_context_size


class GenerateRequest(_SimpleMessage):
    def __init__(self, model_id="", prompt="", messages=None, parameters=None, container_id="", **kwargs):
        self.model_id = model_id
        self.prompt = prompt
        self.messages = messages or []
        self.parameters = parameters or GenerateParameters()
        self.container_id = container_id


class GenerateComplete(_SimpleMessage):
    def __init__(self, full_text="", prompt_tokens=0, completion_tokens=0,
                 prompt_time_seconds=0.0, generation_time_seconds=0.0, tokens_per_second=0.0, **kwargs):
        self.full_text = full_text
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.prompt_time_seconds = prompt_time_seconds
        self.generation_time_seconds = generation_time_seconds
        self.tokens_per_second = tokens_per_second


class GenerateResponse(_SimpleMessage):
    def __init__(self, token=None, complete=None, **kwargs):
        self.token = token
        self.complete = complete
        self._token_set = token is not None
        self._complete_set = complete is not None

    def HasField(self, field_name):
        if field_name == "token":
            return self._token_set
        if field_name == "complete":
            return self._complete_set
        return False


class EmbedRequest(_SimpleMessage):
    def __init__(self, model_id="", texts=None, container_id="", **kwargs):
        self.model_id = model_id
        self.texts = texts or []
        self.container_id = container_id


class Embedding(_SimpleMessage):
    def __init__(self, values=None, **kwargs):
        self.values = values or []


class EmbedResponse(_SimpleMessage):
    def __init__(self, embeddings=None, error="", **kwargs):
        self.embeddings = embeddings or []
        self.error = error


class GetGPUStatusRequest(_SimpleMessage):
    def __init__(self, **kwargs):
        pass


class GetGPUStatusResponse(_SimpleMessage):
    def __init__(self, device_name="", total_memory_bytes=0, used_memory_bytes=0,
                 available_memory_bytes=0, gpu_family="", loaded_models_count=0,
                 loaded_models=None, **kwargs):
        self.device_name = device_name
        self.total_memory_bytes = total_memory_bytes
        self.used_memory_bytes = used_memory_bytes
        self.available_memory_bytes = available_memory_bytes
        self.gpu_family = gpu_family
        self.loaded_models_count = loaded_models_count
        self.loaded_models = loaded_models or []


class PingRequest(_SimpleMessage):
    def __init__(self, **kwargs):
        pass


class PingResponse(_SimpleMessage):
    def __init__(self, status="", version="", uptime_seconds=0.0, **kwargs):
        self.status = status
        self.version = version
        self.uptime_seconds = uptime_seconds
