"""
gRPC client stub for MLXContainerService.

In production, auto-generated by grpc_tools.protoc.
This manual implementation provides the client-side stub.
"""

import grpc

from mlx_container.proto import mlx_container_pb2 as pb2


class MLXContainerServiceStub:
    """Client stub for the MLX Container Service."""

    def __init__(self, channel: grpc.Channel):
        """Initialize with a gRPC channel."""
        self.LoadModel = channel.unary_unary(
            "/mlx_container.v1.MLXContainerService/LoadModel",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.LoadModelResponse),
        )
        self.UnloadModel = channel.unary_unary(
            "/mlx_container.v1.MLXContainerService/UnloadModel",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.UnloadModelResponse),
        )
        self.ListModels = channel.unary_unary(
            "/mlx_container.v1.MLXContainerService/ListModels",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.ListModelsResponse),
        )
        self.Generate = channel.unary_stream(
            "/mlx_container.v1.MLXContainerService/Generate",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.GenerateResponse),
        )
        self.Embed = channel.unary_unary(
            "/mlx_container.v1.MLXContainerService/Embed",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.EmbedResponse),
        )
        self.GetGPUStatus = channel.unary_unary(
            "/mlx_container.v1.MLXContainerService/GetGPUStatus",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.GetGPUStatusResponse),
        )
        self.Ping = channel.unary_unary(
            "/mlx_container.v1.MLXContainerService/Ping",
            request_serializer=_serialize,
            response_deserializer=_make_deserializer(pb2.PingResponse),
        )


def _serialize(msg):
    """Serialize a message to bytes using protobuf."""
    if hasattr(msg, "SerializeToString"):
        return msg.SerializeToString()
    # Fallback: JSON encoding for our simple message classes
    import json
    return json.dumps(msg.__dict__).encode("utf-8")


def _make_deserializer(cls):
    """Create a deserializer function for a message class."""
    def deserialize(data):
        if hasattr(cls, "FromString"):
            try:
                return cls.FromString(data)
            except NotImplementedError:
                pass
        # Fallback: JSON decoding
        import json
        d = json.loads(data.decode("utf-8"))
        return cls(**d)
    return deserialize
